kind: pipeline
name: kernel_santoni

platform:
  os: linux
  arch: amd64

clone:
  depth: 1
###1
steps:
  - name: Compile
    image: kdrag0n/fedora-kbuild:gcc-9.1.1
    commands:
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/zeta96/kernelci/master/lp.sh)"
    when:
      branch:
        - LightPhoenix
